{
    'name': 'Machine Management',
    'version': "19.0.1.0",
    'summary': """Machine Management""",
    'description': """This module is used to Manage machines""",
    'category': 'Machines',
    'author': "Adarsh",
    'website': "www.cybrosys.com",
    'license': "LGPL-3",
    'sequence':-2,
    'installable': True,
    'application': True,
    'auto_install': True,
    'depends': ['mail','product','account','sale_management','website_sale'],
    'data': [
        'security/res_groups.xml',
        'security/ir_rules.xml',
        'security/ir.model.access.csv',
        'static/src/js/action_manager.js',
        'report/machine_management_report.xml',
        'report/machine_management_report_template.xml',
        'data/machine_management_sequence.xml',
        'data/machine_types_data.xml',
        'data/email_template_service.xml',
        'data/recurring_service_creation.xml',
        'wizards/filter_machine_transfer_wizard_view.xml',
        'views/snippets/machine_snippet_views.xml',
        'views/create_customer_form_views.xml',
        'views/portal_templates.xml',
        'views/create_service_form_views.xml',
        'views/res_partner_views.xml',
        'views/machine_management_order_line_views.xml',
        'views/machine_service_views.xml',
        'views/machine_transfer_views.xml',
        'views/machine_management_views.xml',
        'views/machine_management_menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'machine_management/static/src/js/action_manager.js'
        ],
        'web.assets_frontend': [
            'machine_management/static/src/xml/machine_catalogue.xml',
            'machine_management/static/src/js/machine_snippet.js',
       ],
    }
}